export const SIGNUP_POST_API_V1_SIGNUP_READ = "SIGNUP_POST_API_V1_SIGNUP_READ"
export const SIGNUP_POST_API_V1_SIGNUP_READ_SUCCEEDED =
  "SIGNUP_POST_API_V1_SIGNUP_READ_SUCCEEDED"
export const SIGNUP_POST_API_V1_SIGNUP_READ_FAILED =
  "SIGNUP_POST_API_V1_SIGNUP_READ_FAILED"
