export const SIGNUP_POST_API_V1_SIGNUP_CREATE =
  "SIGNUP_POST_API_V1_SIGNUP_CREATE"
export const SIGNUP_POST_API_V1_SIGNUP_CREATE_SUCCEEDED =
  "SIGNUP_POST_API_V1_SIGNUP_CREATE_SUCCEEDED"
export const SIGNUP_POST_API_V1_SIGNUP_CREATE_FAILED =
  "SIGNUP_POST_API_V1_SIGNUP_CREATE_FAILED"
